name: "Build"

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  docker-image:
    name: "Docker image"
    runs-on: ubuntu-latest

    steps:

      - name: "Define the Docker image version"
        id: image_version
        run: |
          if [[ "${GITHUB_REF}" =~ 'refs/tags/' ]]
          then
            echo IMAGE_VERSION=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT
          else
            echo IMAGE_VERSION=latest >> $GITHUB_OUTPUT
          fi

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to DockerHub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push"
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
          tags: xstefanox/swarmcret:${{ steps.image_version.outputs.IMAGE_VERSION }}
